### ISSUE TITLE
Payment and Moderation secrets

### ISSUE THREAD

**Issue by Egoistically** [see-aestas/SinoAliceApi#1]
Tried hooking `Alice.Config.EnvironmentDefineUsReview`'s `GetModerationAppSecret` and `GetPaymentAppSecret` with Frida and got two 64 bytes strings, so I thought they were the correct ones. However, I am getting `Invalid Signature` on bn-payment.

Am I hooking the wrong functions or is my whole approach incorrect?
Also, was I supposed to modify the `RSA.generate` function to allow 512 bit generation?

Thanks in advance.

**Comment by 8mas** [comment]
Hooking is a good approach.
You might get this error because:
1. You specified an old app version
2. Wrong app id

I added the secrets.py as a help. 
All "secrets" that need to reverse-engineered are listed there. 
To make it easier you can check the first bytes to see if you got the right secret.


Yes, for compliance with the API we need to change RSA.py to allow 512-bit keys. 
I added this to the readme, thanks :)

**Comment by Egoistically** [comment]
Updated everything and gave it another try to see if that was the problem, but those two functions return strings completely different to yours.
I got the AES key without any problem by hooking the decryption, but payment and moderation secrets are giving me such a headache.

Thanks for helping me, I'm really new to all of these. 
Btw, here you have my discord if you prefer talking over there: Shirome#4083.

Edit: Tried hooking `GreeGameLib.Payment.initialize()` (which is called in `Aries.GameLib.Initializer.Initialize` and uses `applicationSecret` as an argument) and a few more functions, none of them giving me the expected result. 
This is part of the string I'm getting everywhere: `OdzM+V8NWSUhj...`.

What am I doing wrong?

**Comment by 8mas** [comment]
The secrets I reverse-engineered are about two months old and from Android (they still work). 
It is possible that they have changed their secrets in the meantime.

Some secrets are encrypted to prevent them from being stored in plaintext.

Try hooking a function that needs to work with the plain key (e.g. the functions for signing data).

**Comment by Egoistically** [comment]
The AES key remains the same, so the secrets shouldn't have changed.
And yeah, the ones I'm getting are most likely encrypted. 

~~Tried hooking a signing function, but it's for signing API calls. Can't really find the proper one~~. Edit: Didn't bother checking encodings, I'm actually dumb :^).
Will try hooking other stuff and debugging with IDA, hopefully I end up finding the actual ones.

Thank you for your help.

**Comment by Egoistically** [comment]
Thanks for the small hints, ended up getting them.
